import { createFileRoute } from "@tanstack/react-router"
import { useMutation, useQuery } from "convex/react"
import { api } from "@/convex/_generated/api"
import { AuthGate } from "@/components/auth-gate"
import { useState } from "react"

export const Route=createFileRoute("/")({component:()=> <AuthGate><App/></AuthGate>})
const BRANCH_ID="BR-A"; const ORG_ID="ORG-DEMO"
function App(){
 const result=useQuery(api.permits.listScoped,{branchId:BRANCH_ID,limit:50}); const createPermit=useMutation(api.permits.createScoped); const updateState=useMutation(api.permits.updateStateScoped); const [busy,setBusy]=useState(false)
 async function addSeed(){setBusy(true);try{await createPermit({permitId:`SEED-${Date.now()}`,type:"HOT_WORK",location:"TEST-AREA-B",organizationId:ORG_ID,branchId:BRANCH_ID,requiresLoto:true,requiredGasTest:true,dataClass:"TEST/SEED"})}finally{setBusy(false)}}
 async function advance(p:any){setBusy(true);const b={id:p._id,branchId:BRANCH_ID,authorizationApproved:p.authorizationApproved,lotoApplied:p.lotoApplied,lotoReleased:p.lotoReleased,gasTestPassed:p.gasTestPassed};try{if(p.status==="REQUESTED")return await updateState({...b,status:"PENDING_APPROVAL"});if(p.status==="PENDING_APPROVAL")return await updateState({...b,status:"ISSUED",authorizationApproved:true});if(p.status==="ISSUED"){if(p.requiresLoto&&!p.lotoApplied)return await updateState({...b,status:"ISSUED",lotoApplied:true});if(p.requiredGasTest&&!p.gasTestPassed)return await updateState({...b,status:"ISSUED",gasTestPassed:true});return await updateState({...b,status:"ACTIVE"})}if(p.status==="ACTIVE")return await updateState({...b,status:"SUSPENDED"});if(p.status==="SUSPENDED")return await updateState({...b,status:"RESUMED"});if(p.status==="RESUMED"&&p.requiresLoto&&!p.lotoReleased)return await updateState({...b,status:"RESUMED",lotoReleased:true});if(p.status==="RESUMED")return await updateState({...b,status:"CLOSED"})}finally{setBusy(false)}}
 const permits=result?.ok?result.permits:[]; const access=result?.ok?"Scope شعبه مجاز است":result?`دسترسی: ${result.code}`:"در حال بررسی دسترسی…"
 return <main dir="rtl" className="min-h-screen bg-slate-50 text-slate-900"><div className="flex min-h-screen"><aside className="hidden w-64 shrink-0 bg-slate-950 p-5 text-white lg:flex lg:flex-col"><div className="mb-8 text-2xl font-bold">ایمن بندر</div><nav className="space-y-1">{["داشبورد","مجوز کار","بازرسی‌ها","حوادث و CAPA","ریسک","آموزش و صلاحیت","محیط‌زیست","گزارش‌ها"].map((x,i)=><div key={x} className={`rounded-xl px-4 py-3 text-sm ${i===0?"bg-white/10":"text-slate-300"}`}>{x}</div>)}</nav><div className="mt-auto rounded-2xl bg-white/5 p-4 text-xs">سازمان: {ORG_ID}<br/>شعبه: {BRANCH_ID}</div></aside><section className="min-w-0 flex-1"><header className="border-b bg-white p-5"><div className="mx-auto flex max-w-[1500px] items-center justify-between"><div><div className="text-sm text-slate-500">مدیریت ایمنی، بهداشت و محیط‌زیست</div><h1 className="mt-1 text-2xl font-bold">داشبورد HSE</h1></div><div className="flex gap-2"><span className="rounded-full border px-3 py-2 text-xs">{access}</span><button onClick={addSeed} disabled={busy||!result?.ok} className="rounded-xl bg-slate-900 px-4 py-2 text-sm text-white disabled:opacity-40">مجوز تست</button></div></div></header><div className="mx-auto max-w-[1500px] space-y-6 p-5 lg:p-8"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{["مجوزهای فعال","بازرسی‌های امروز","اقدامات باز","حوادث"].map((x)=><div key={x} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="text-2xl font-bold">—</div><div className="mt-1 text-sm text-slate-600">{x}</div></div>)}</div><div className="rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="text-xl font-bold">مجوزهای PTW</h2><p className="mt-1 text-sm text-slate-500">Authorization + LOTO + Gas Test + Scope</p></div>{permits.length===0?<div className="p-12 text-center text-sm text-slate-500">هنوز رکورد قابل مشاهده‌ای وجود ندارد.</div>:<div className="overflow-x-auto"><div className="min-w-[850px]"><div className="grid grid-cols-7 gap-3 bg-slate-50 px-5 py-3 text-xs font-semibold"><div>شناسه</div><div>نوع</div><div>محل</div><div>Scope</div><div>وضعیت</div><div>داده</div><div>عملیات</div></div>{permits.map((p:any)=><div key={p._id} className="grid grid-cols-7 items-center gap-3 border-t px-5 py-4 text-sm"><div>{p.permitId}</div><div>{p.type}</div><div>{p.location}</div><div>{p.branchId}</div><div>{p.status}</div><div>{p.dataClass}</div><button onClick={()=>advance(p)} disabled={busy||p.status==="CLOSED"} className="rounded-lg border px-3 py-2 text-xs disabled:opacity-40">گام بعدی</button></div>)}</div></div>}</div></div></section></div></main>
}
