import { describe, it, expect } from "vitest"
import { convexTest } from "convex-test"
import schema from "../../convex/schema"
import { api } from "../../convex/_generated/api"

function makeT(){ return convexTest(schema, import.meta.glob("../../convex/**/*.*s")) }
const FULL_SCOPE = { organizationId:"ORG-DEMO", regionId:"REG-DEMO", branchId:"BR-A", siteId:"SITE-DEMO", unitId:"UNIT-DEMO" }
async function seedProfile(t:any, role:"CENTRAL_HSE"|"BRANCH_MANAGER"|"HSE_SUPERVISOR"|"HSE_STAFF"|"OPERATIONS_STAFF"|"CONTRACTOR", scope:{organizationId:string;regionIds:string[];branchIds:string[];siteIds:string[];unitIds:string[]}){ return await t.run(async(ctx:any)=>{ const userId=await ctx.db.insert("users",{}); await ctx.db.insert("userProfiles",{userId,identitySubject:userId,role,organizationId:scope.organizationId,regionIds:scope.regionIds,branchIds:scope.branchIds,siteIds:scope.siteIds,unitIds:scope.unitIds,active:true}); return userId }) }
const FULL_MATCH = { organizationId:"ORG-DEMO", regionIds:["REG-DEMO"], branchIds:["BR-A"], siteIds:["SITE-DEMO"], unitIds:["UNIT-DEMO"] }

describe("D08 PTW C03 authorization boundary",()=>{
 it("denies unauthenticated branch reads",async()=>{ const t=makeT(); const result=await t.query(api.permits.listScoped,FULL_SCOPE); expect(result).toMatchObject({ok:false,code:"UNAUTHENTICATED"}) })
 it("denies authenticated user outside branch scope",async()=>{ const t=makeT(); const user=await seedProfile(t,"HSE_STAFF",{...FULL_MATCH,branchIds:["BR-B"]}); const result=await t.withIdentity({subject:user}).query(api.permits.listScoped,FULL_SCOPE); expect(result).toMatchObject({ok:false,code:"BRANCH_SCOPE_DENIED"}) })
 it("allows read inside full authorized scope",async()=>{ const t=makeT(); const user=await seedProfile(t,"HSE_STAFF",FULL_MATCH); const result=await t.withIdentity({subject:user}).query(api.permits.listScoped,FULL_SCOPE); expect(result).toMatchObject({ok:true,permits:[]}) })
 it("enforces role permission on PTW creation",async()=>{ const t=makeT(); const user=await seedProfile(t,"CONTRACTOR",FULL_MATCH); const result=await t.withIdentity({subject:user}).mutation(api.permits.createScoped,{permitId:"T-001",type:"HOT_WORK",location:"AREA-A",...FULL_SCOPE,activityDescription:"Hot work",requester:"R-1",responsiblePerson:"RP-1",requiresLoto:true,requiredGasTest:true,dataClass:"OPERATIONAL"}); expect(result).toMatchObject({ok:true}) })
 it("denies wrong organization",async()=>{ const t=makeT(); const user=await seedProfile(t,"HSE_STAFF",{...FULL_MATCH,organizationId:"ORG-OTHER"}); const result=await t.withIdentity({subject:user}).query(api.permits.listScoped,FULL_SCOPE); expect(result).toMatchObject({ok:false,code:"ORGANIZATION_SCOPE_DENIED"}) })
 it("denies wrong region",async()=>{ const t=makeT(); const user=await seedProfile(t,"HSE_STAFF",{...FULL_MATCH,regionIds:["REG-OTHER"]}); const result=await t.withIdentity({subject:user}).query(api.permits.listScoped,FULL_SCOPE); expect(result).toMatchObject({ok:false,code:"REGION_SCOPE_DENIED"}) })
 it("denies wrong site",async()=>{ const t=makeT(); const user=await seedProfile(t,"HSE_STAFF",{...FULL_MATCH,siteIds:["SITE-OTHER"]}); const result=await t.withIdentity({subject:user}).query(api.permits.listScoped,FULL_SCOPE); expect(result).toMatchObject({ok:false,code:"SITE_SCOPE_DENIED"}) })
 it("denies wrong unit",async()=>{ const t=makeT(); const user=await seedProfile(t,"HSE_STAFF",{...FULL_MATCH,unitIds:["UNIT-OTHER"]}); const result=await t.withIdentity({subject:user}).query(api.permits.listScoped,FULL_SCOPE); expect(result).toMatchObject({ok:false,code:"UNIT_SCOPE_DENIED"}) })
 it("CENTRAL_HSE bypasses all scope restrictions",async()=>{ const t=makeT(); const user=await seedProfile(t,"CENTRAL_HSE",{organizationId:"ORG-OTHER",regionIds:[],branchIds:[],siteIds:[],unitIds:[]}); const result=await t.withIdentity({subject:user}).query(api.permits.listScoped,FULL_SCOPE); expect(result).toMatchObject({ok:true}) })
 it("filters out a permit whose site is outside the reader's site scope even with correct branch",async()=>{ const t=makeT(); const creator=await seedProfile(t,"CENTRAL_HSE",{organizationId:"ORG-DEMO",regionIds:[],branchIds:[],siteIds:[],unitIds:[]}); const created=await t.withIdentity({subject:creator}).mutation(api.permits.createScoped,{permitId:"SITE-VIS-001",type:"COLD_WORK",location:"AREA-B",...FULL_SCOPE,siteId:"SITE-OTHER",activityDescription:"Cold work",requester:"R-1",responsiblePerson:"RP-1",requiresLoto:false,requiredGasTest:false,dataClass:"OPERATIONAL"}); expect(created).toMatchObject({ok:true}); const reader=await seedProfile(t,"HSE_STAFF",FULL_MATCH); const result:any=await t.withIdentity({subject:reader}).query(api.permits.listScoped,FULL_SCOPE); expect(result.ok).toBe(true); expect(result.permits.find((p:any)=>p.permitId==="SITE-VIS-001")).toBeUndefined() })
 it("shows a permit whose site matches the reader's site scope",async()=>{ const t=makeT(); const creator=await seedProfile(t,"HSE_SUPERVISOR",FULL_MATCH); await t.withIdentity({subject:creator}).mutation(api.permits.createScoped,{permitId:"SITE-VIS-002",type:"COLD_WORK",location:"AREA-B",...FULL_SCOPE,activityDescription:"Cold work",requester:"R-1",responsiblePerson:"RP-1",requiresLoto:false,requiredGasTest:false,dataClass:"OPERATIONAL"}); const reader=await seedProfile(t,"HSE_STAFF",FULL_MATCH); const result:any=await t.withIdentity({subject:reader}).query(api.permits.listScoped,FULL_SCOPE); expect(result.permits.find((p:any)=>p.permitId==="SITE-VIS-002")).toBeDefined() })
})
